version: "3.5"
services:
  core:
    build: ./core/
    image: ansible-lab-core
    networks:
      ansible:
  master:
    build:
      context: ./master/
      args:
        UID: ${UID}
        GID: ${GID}
    image: ansible-lab-master
    container_name: ansible-master
    hostname: ansible-master
    user: ${UID}:${GID}
    networks:
      ansible:
        aliases:
          - master
    volumes:
      - type: bind
        source: ./ansible
        target: /opt/ansible
      - type: volume
        source: ansible-sshkeys
        target: /mnt/ansible-sshkeys
    depends_on:
      - core
  node1:
    build: ./node/
    image: ansible-lab-node
    container_name: ansible-node1
    hostname: ansible-node1
    networks:
      ansible:
        aliases:
          - node1
    volumes:
      - type: volume
        source: ansible-sshkeys
        target: /mnt/ansible-sshkeys
        read_only: true
    depends_on:
      - core
  node2:
    image: ansible-lab-node
    container_name: ansible-node2
    hostname: ansible-node2
    networks:
      ansible:
        aliases:
          - node2
    volumes:
      - type: volume
        source: ansible-sshkeys
        target: /mnt/ansible-sshkeys
        read_only: true
    depends_on:
      - node1

networks:
  ansible:
    driver: bridge
    name: ansible

volumes:
  ansible-sshkeys:
    driver: local
    name: ansible-sshkeys
